---
title: "About"
---

The goal of this creative coding workshop is so that we can create a space where we (at ANU) can commune to discuss coding while having some fun with art. If this workshop is successful, there may be opportunities to repeat this in the future and in essence, create a community where creative coders can connect. We would also love to showcase the generative art you create on this website!

While the primary materials are geared towards those who are proficient in R, those who want to come and join are welcomed!


## Mental Health Awareness Month

Mental Health Awareness Month is a Month dedicated to raising awareness of the risk factors for Mental Health Conditions and the connections between mental and physical health. One of the key focuses during this month is to bring awareness to noticing signs of mental health conditions as they arise, letting people know how and who they can ask for help, and giving people ideas and resources on how to maintain their mental health. Whilst Mental Health Awareness month is just one month of the year, the things you can learn during the month can be used and practiced throughout the year.

For more details see the [College of Science intranet on wellbeing](https://intranet.science.anu.edu.au/services-resources/wellbeing).

## Acknowledgement


Thank you to **Nat Thomas**, Senior Advisor for Diversity and Culture at CoS, for booking us the room and organising the afternoon tea for this activity.

This website is built using **Quarto** and hosted using **GitHub pages**. All code to make this website can be found [here](https://github.com/anu-links/creative-coding).


## Formal study

For those interested in formal study about creative coding, you may want to check out the following courses:

- **Foundations of Creative Code** [DESN2002](https://programsandcourses.anu.edu.au/course/DESN2002) or [DESN6002](https://programsandcourses.anu.edu.au/course/DESN6002)
- **Art and Interaction Computing** [COMP1720](https://programsandcourses.anu.edu.au/2021/course/COMP1720)
